import { ExtractedCandidate, NormalizedSearchFilters } from "@/lib/msp/types";

const MOCK_COMPANIES: ExtractedCandidate[] = [
  {
    companyName: "Desert Ridge Managed IT",
    website: "https://www.desertridgeit.com",
    headquartersCity: "Phoenix",
    headquartersState: "AZ",
    employeeCountExact: 72,
    employeeCountMin: null,
    employeeCountMax: null,
    companySizeTier: "small",
    awsSupport: true,
    azureSupport: true,
    awsPartnerClaimed: true,
    azurePartnerClaimed: true,
    awsResellerConfirmed: true,
    azureResellerConfirmed: false,
    isMsp: true,
    disqualifierType: null,
    sources: [
      {
        url: "https://www.desertridgeit.com/services/managed-it",
        title: "Managed IT Services",
        sourceType: "official_website",
        claim: "Company website lists managed IT support, cybersecurity, and cloud operations services.",
        supportsMsp: true,
        supportsAws: false,
        supportsAzure: false,
        supportsEmployeeCount: false,
        supportsHeadquarters: false,
      },
      {
        url: "https://www.desertridgeit.com/cloud/azure",
        title: "Azure Cloud Solutions",
        sourceType: "official_website",
        claim: "Azure migration and Microsoft 365 managed services are listed on the official solutions page.",
        supportsMsp: false,
        supportsAws: false,
        supportsAzure: true,
        supportsEmployeeCount: false,
        supportsHeadquarters: false,
      },
      {
        url: "https://partners.amazonaws.com/partners/001A000000xDesert",
        title: "AWS Partner Listing",
        sourceType: "partner_directory",
        claim: "AWS partner listing shows an active consulting and reseller relationship.",
        supportsMsp: false,
        supportsAws: true,
        supportsAzure: false,
        supportsEmployeeCount: false,
        supportsHeadquarters: false,
      },
      {
        url: "https://www.linkedin.com/company/desert-ridge-managed-it",
        title: "LinkedIn",
        sourceType: "linkedin",
        claim: "LinkedIn profile shows headquarters in Phoenix, AZ and approximately 72 employees.",
        supportsMsp: false,
        supportsAws: false,
        supportsAzure: false,
        supportsEmployeeCount: true,
        supportsHeadquarters: true,
      },
    ],
  },
  {
    companyName: "Cascade Business Technology",
    website: "https://www.cascadebusinesstech.com",
    headquartersCity: "Portland",
    headquartersState: "OR",
    employeeCountExact: null,
    employeeCountMin: 45,
    employeeCountMax: 80,
    companySizeTier: "small",
    awsSupport: true,
    azureSupport: false,
    awsPartnerClaimed: true,
    azurePartnerClaimed: false,
    awsResellerConfirmed: false,
    azureResellerConfirmed: false,
    isMsp: true,
    disqualifierType: null,
    sources: [
      {
        url: "https://www.cascadebusinesstech.com/managed-services",
        title: "Managed Services",
        sourceType: "official_website",
        claim: "Managed help desk, vCIO, and network monitoring services are listed on the company website.",
        supportsMsp: true,
        supportsAws: false,
        supportsAzure: false,
        supportsEmployeeCount: false,
        supportsHeadquarters: false,
      },
      {
        url: "https://www.cascadebusinesstech.com/cloud/aws",
        title: "AWS Services",
        sourceType: "official_website",
        claim: "Cloud page references AWS migration planning and managed AWS operations.",
        supportsMsp: false,
        supportsAws: true,
        supportsAzure: false,
        supportsEmployeeCount: false,
        supportsHeadquarters: false,
      },
      {
        url: "https://www.linkedin.com/company/cascade-business-technology",
        title: "LinkedIn",
        sourceType: "linkedin",
        claim: "LinkedIn profile lists Portland, OR headquarters and a 45-80 employee range.",
        supportsMsp: false,
        supportsAws: false,
        supportsAzure: false,
        supportsEmployeeCount: true,
        supportsHeadquarters: true,
      },
    ],
  },
  {
    companyName: "Summit Harbor MSP",
    website: "https://www.summitharbormsp.com",
    headquartersCity: "Denver",
    headquartersState: "CO",
    employeeCountExact: 33,
    employeeCountMin: null,
    employeeCountMax: null,
    companySizeTier: "small",
    awsSupport: false,
    azureSupport: true,
    awsPartnerClaimed: false,
    azurePartnerClaimed: true,
    awsResellerConfirmed: false,
    azureResellerConfirmed: true,
    isMsp: true,
    disqualifierType: null,
    sources: [
      {
        url: "https://www.summitharbormsp.com/services",
        title: "Services",
        sourceType: "official_website",
        claim: "Service catalog lists managed IT, security monitoring, and endpoint management plans.",
        supportsMsp: true,
        supportsAws: false,
        supportsAzure: false,
        supportsEmployeeCount: false,
        supportsHeadquarters: false,
      },
      {
        url: "https://www.summitharbormsp.com/microsoft-partner",
        title: "Microsoft Partner",
        sourceType: "official_website",
        claim: "Company website identifies the firm as a Microsoft Solutions Partner for Modern Work.",
        supportsMsp: false,
        supportsAws: false,
        supportsAzure: true,
        supportsEmployeeCount: false,
        supportsHeadquarters: false,
      },
      {
        url: "https://www.linkedin.com/company/summit-harbor-msp",
        title: "LinkedIn",
        sourceType: "linkedin",
        claim: "LinkedIn page reports Denver, CO headquarters and 33 employees.",
        supportsMsp: false,
        supportsAws: false,
        supportsAzure: false,
        supportsEmployeeCount: true,
        supportsHeadquarters: true,
      },
    ],
  },
  {
    companyName: "Bluegrid Talent Placement",
    website: "https://www.bluegridtalent.com",
    headquartersCity: "Austin",
    headquartersState: "TX",
    employeeCountExact: null,
    employeeCountMin: null,
    employeeCountMax: null,
    companySizeTier: null,
    awsSupport: false,
    azureSupport: false,
    awsPartnerClaimed: false,
    azurePartnerClaimed: false,
    awsResellerConfirmed: false,
    azureResellerConfirmed: false,
    isMsp: false,
    disqualifierType: "recruiter",
    sources: [
      {
        url: "https://www.bluegridtalent.com/about",
        title: "About",
        sourceType: "official_website",
        claim: "Website describes the company as a technical staffing and recruiting firm.",
        supportsMsp: false,
        supportsAws: false,
        supportsAzure: false,
        supportsEmployeeCount: false,
        supportsHeadquarters: false,
      },
    ],
  },
];

export function buildMockCandidates(
  filters: NormalizedSearchFilters,
): ExtractedCandidate[] {
  const limit = Math.max(filters.resultLimit * 2, 6);
  return MOCK_COMPANIES.slice(0, limit);
}
